In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('AUROPHARMAEQN.csv',usecols=[0,2,9])

In [3]:
def buy():
    global amount,p,flags,rate,depth
    try:
        money = amount/(depth-len(flags))
        amount -= money
        quantity=money//p
        amount += money%p
        flags.append({'cost':p,'qty':quantity})
        return p*(1+rate),p*(1-rate)
    except:
        return target,sl

def sell():
    global flags,amount,p,rate,depth
    a=flags.pop()
    amount+=p*a['qty']
    q=0
    try:
        q=flags[-1]['cost'] 
    except: pass
    return q*(1+rate),q*(1-rate)

In [4]:
amount = 500000
rate=.02
depth=5
records=[]
flags = []
for p in data.Average_Price:
    action=None
    if len(flags) == 0:
        target,sl=buy()
        action='buy'
    elif p>=target:
        target,sl=sell()
        action='sell'
    elif p <= sl :
        target,sl = buy()
        action='buy'
    records.append([amount,action,amount+sum([i['qty'] for i in flags ])*p,len(flags),str(flags)])

In [5]:
final=data.join(pd.DataFrame(records,columns=['amount','action','currentvalue','depth','flags']))

In [6]:
final

,Symbol,Date,Average_Price,amount,action,currentvalue,depth,flags
0,AUROPHARMA,07-Apr-2020,423.40,400077.60,buy,500000.00,1,"[{'cost': 423.4, 'qty': 236.0}]"
1,AUROPHARMA,08-Apr-2020,449.38,506131.28,sell,506131.28,0,[]
2,AUROPHARMA,09-Apr-2020,461.88,404979.56,buy,506131.28,1,"[{'cost': 461.88, 'qty': 219.0}]"
3,AUROPHARMA,13-Apr-2020,493.30,513012.26,sell,513012.26,0,[]
4,AUROPHARMA,15-Apr-2020,522.06,410688.50,buy,513012.26,1,"[{'cost': 522.06, 'qty': 196.0}]"
...,...,...,...,...,...,...,...,...
492,AUROPHARMA,29-Mar-2022,692.45,434.29,buy,519079.34,5,"[{'cost': 1038.18, 'qty': 134.0}, {'cost': 100..."
493,AUROPHARMA,30-Mar-2022,679.24,434.29,buy,509185.05,5,"[{'cost': 1038.18, 'qty': 134.0}, {'cost': 100..."
494,AUROPHARMA,31-Mar-2022,672.40,434.29,buy,504061.89,5,"[{'cost': 1038.18, 'qty': 134.0}, {'cost': 100..."
495,AUROPHARMA,01-Apr-2022,676.83,434.29,buy,507379.96,5,"[{'cost': 1038.18, 'qty': 134.0}, {'cost': 100..."
496,AUROPHARMA,04-Apr-2022,689.11,434.29,buy,516577.68,5,"[{'cost': 1038.18, 'qty': 134.0}, {'cost': 100..."

In [112]:
final.to_excel('check.xlsx')